// generated by derplanner [http://www.github.com/alexshafranov/derplanner]
#include "derplanner/runtime/domain_support.h"
#include "run_8.h"

using namespace plnnr;

#ifdef __GNUC__
#pragma GCC diagnostic ignored "-Wunused-parameter"
#pragma GCC diagnostic ignored "-Wunused-variable"
#endif

#ifdef _MSC_VER
#pragma warning(disable: 4100) // unreferenced formal parameter
#pragma warning(disable: 4189) // local variable is initialized but not referenced
#endif

static bool attack_all_visible_case_0(Planning_State*, Expansion_Frame*, Fact_Database*);

static Composite_Task_Expand* s_task_expands[] = {
  attack_all_visible_case_0,
};

static const char* s_fact_names[] = {
  "me",
  "object",
 };

static const char* s_task_names[] = {
  "attack!",
  "attack_all_visible",
 };

static Fact_Type s_fact_types[] = {
  { 2, {Type_Vec3, Type_Vec3, } },
  { 2, {Type_Id32, Type_Vec3, } },
};

static Type s_layout_types[] = {
  Type_Id32,
  Type_Vec3,
  Type_Vec3,
  Type_Id32,
  Type_Vec3,
};

static size_t s_layout_offsets[5];

static Param_Layout s_task_parameters[] = {
  { 1, s_layout_types + 0, 0, s_layout_offsets + 0 },
  { 0, 0, 0, 0 },
};

static Param_Layout s_bindings[] = {
  { 4, s_layout_types + 1, 0, s_layout_offsets + 0 },
};

static uint32_t s_num_cases[] = {
  1, 
};

static uint32_t s_first_case[] = {
  0, 
};

static uint32_t s_size_hints[] = {
  0, 
  0, 
};

static uint32_t s_num_case_handles[] = {
  2, 
};

static uint32_t s_fact_name_hashes[] = {
  2759711470, 
  2627410831, 
};

static uint32_t s_task_name_hashes[] = {
  1438593975, 
  55566473, 
};

static Domain_Info s_domain_info = {
  { 2, 1, 1, s_num_cases, s_first_case, 0, s_task_name_hashes, s_task_names, s_task_parameters, s_bindings, s_num_case_handles, s_task_expands },
  { 2, 0, s_size_hints, s_fact_types, s_fact_name_hashes, s_fact_names },
};

void run_8_init_domain_info()
{
  for (size_t i = 0; i < plnnr_static_array_size(s_task_parameters); ++i) {
    compute_offsets_and_size(s_task_parameters[i]);
  }

  for (size_t i = 0; i < plnnr_static_array_size(s_bindings); ++i) {
    compute_offsets_and_size(s_bindings[i]);
  }
}

const Domain_Info* run_8_get_domain_info() { return &s_domain_info; }

struct S_1 {
  Vec3 _0;
  Vec3 _1;
  Id32 _2;
  Vec3 _3;
};

static bool p0_next(Planning_State* state, Expansion_Frame* frame, Fact_Database* db)
{
  Fact_Handle* handles = frame->handles;
  S_1* binds = (S_1*)(frame->bindings);

  plnnr_coroutine_begin(frame, precond_label);

  for (handles[0] = first(db, 0); is_valid(db, handles[0]); handles[0] = next(db, handles[0])) { // me
    binds->_0 = Vec3(as_Vec3(db, handles[0], 0));
    binds->_1 = Vec3(as_Vec3(db, handles[0], 1));
    for (handles[1] = first(db, 1); is_valid(db, handles[1]); handles[1] = next(db, handles[1])) { // object
      binds->_2 = Id32(as_Id32(db, handles[1], 0));
      binds->_3 = Vec3(as_Vec3(db, handles[1], 1));
      if (bool((plnnr::dot(Vec3(plnnr::norm(Vec3((binds->_3 - binds->_0)))), Vec3(binds->_1)) >= plnnr::cos(float((plnnr::pi() / 4.0)))))) {
        plnnr_coroutine_yield(frame, precond_label, 1);
      }
    }
  }

  plnnr_coroutine_end();
}

static bool attack_all_visible_case_0(Planning_State* state, Expansion_Frame* frame, Fact_Database* db)
{
  const S_1* binds = (const S_1*)(frame->bindings);

  plnnr_coroutine_begin(frame, expand_label);

  while (p0_next(state, frame, db)) {
    begin_task(state, &s_domain_info, 0); // attack!
    set_task_arg(state, s_task_parameters[0], 0, Id32(binds->_2));
    plnnr_coroutine_yield(frame, expand_label, 1);

    continue_iteration(state, frame);
  }

  if (frame->status == Expansion_Frame::Status_Was_Expanded) {
    frame->status = Expansion_Frame::Status_Expanded;
    plnnr_coroutine_yield(frame, expand_label, 2);
  }

  plnnr_coroutine_end();
}

