// generated by derplanner [http://www.github.com/alexshafranov/derplanner]
#ifndef run_8_H_
#define run_8_H_
#pragma once

#include "derplanner/runtime/types.h"

#ifndef PLNNR_DOMAIN_API
#define PLNNR_DOMAIN_API
#endif

extern "C" PLNNR_DOMAIN_API void run_8_init_domain_info();
extern "C" PLNNR_DOMAIN_API const plnnr::Domain_Info* run_8_get_domain_info();

#endif
