// generated by derplanner [http://www.github.com/alexshafranov/derplanner]
#ifndef run_4_H_
#define run_4_H_
#pragma once

#include "derplanner/runtime/types.h"

#ifndef PLNNR_DOMAIN_API
#define PLNNR_DOMAIN_API
#endif

extern "C" PLNNR_DOMAIN_API void run_4_init_domain_info();
extern "C" PLNNR_DOMAIN_API const plnnr::Domain_Info* run_4_get_domain_info();

#endif
